name: Build Résumé

on:
  push:
    branches:
      - main
    paths:
      - "**.tex"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: var
        run: |
          PDF_NAME="gaurav_chauhan"
          echo "pdf_name=$PDF_NAME" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build résumé
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          args: -pdf -interaction=nonstopmode -synctex=1

      - name: Rename PDF
        run: mv main.pdf "${{ steps.var.outputs.pdf_name }}.pdf"

      - name: Upload résumé
        uses: softprops/action-gh-release@v3
        with:
          files: "${{ steps.var.outputs.pdf_name }}.pdf"
          tag_name: "v${{ steps.var.outputs.timestamp }}"
          name: ${{ steps.var.outputs.timestamp }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
