name: Build Résumé

on:
  push:
    branches:
      - main
    paths:
      - "**.typ"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Typst
        uses: typst-community/setup-typst@v5

      - name: Build resume
        run: typst compile main.typ gaurav_chauhan.pdf

      - name: Upload resume
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          files: "gaurav_chauhan.pdf"
          name: Build ${{ github.run_number }}
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}